//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AramisIDE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AramisIDE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Aramis.Attributes;
        ///using Aramis.DatabaseConnector;
        ///using Aramis.Enums;
        ///using Aramis.Core;
        ///using Aramis.SystemConfigurations;
        ///using Catalogs;
        ///
        ///namespace Catalogs
        ///    {{    
        ///    [Catalog(Description = &quot;&quot;, GUID = &quot;{0}&quot;, DescriptionSize = 35, HierarchicType = HierarchicTypes.None)]
        ///    public class {1} : CatalogTable
        ///        {{
        ///        public {1}()
        ///            : base()
        ///            {{
        ///            
        ///            }}
        ///        }}
        ///    }}.
        /// </summary>
        internal static string CatalogTemplate {
            get {
                return ResourceManager.GetString("CatalogTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Aramis.Attributes;
        ///using Aramis.DatabaseConnector;
        ///using Aramis.Enums;
        ///using Aramis.Core;
        ///using Aramis.SystemConfigurations;
        ///using Catalogs;
        ///
        ///namespace Documents
        ///    {{    
        ///    [Document(Description = &quot;&quot;, GUID = &quot;{0}&quot;)]
        ///    public class {1} : DocumentTable
        ///        {{
        ///        public {1}()
        ///            : base()
        ///            {{
        ///            
        ///            }}
        ///        }}
        ///    }}.
        /// </summary>
        internal static string DocumentTemplate {
            get {
                return ResourceManager.GetString("DocumentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ProgramIcon {
            get {
                object obj = ResourceManager.GetObject("ProgramIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
